name: boot_factory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  fluent_ui: ^4.8.6
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_colorpicker: ^1.0.3
  flutter_hsvcolor_picker: ^1.5.0
  go_router: ^13.2.0
  image: ^4.1.7
  provider: ^6.1.1
  reorderables: ^0.6.0
  system_theme: ^2.3.1
  uuid: ^4.3.3
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
  assets:
  - assets/
  - assets/icons/